"""Financial Synthesis Node with Sentence-Level Citation Tagging.

Primary path (`settings.llm_backend == "local_cli"`, the default): the draft
is generated by a real locally-installed AI CLI (claude / antigravity /
opencode — see `src.llm.cli_provider`), grounded strictly in the retrieved
chunks and financial metrics via a prompt that mirrors the citation format
`citation_verifier` expects (`[chunk_id]` per fact-bearing sentence).

Cloud fallback (opt-in, tried after local CLI): if local CLI is disabled,
unavailable, or every provider fails, and `settings.llm_cloud_fallback_order`
lists at least one provider, Azure OpenAI / Google Vertex AI is tried next
(see `src.llm.cloud_provider`). This is empty by default — local CLI keeps
priority and this stage is a no-op unless an operator explicitly configures
cloud credentials.

Final fallback path: if neither local CLI nor any configured cloud provider
produced a draft, a deterministic rule-based sentence assembler
(`synthesize_grounded_response`) is used instead — no LLM call, always
succeeds, and is what the test suite exercises (see tests/conftest.py).
"""

import logging
import time
from typing import Any, Dict, List, Optional, Tuple

from config.settings import settings
from src.citation.extractor import macro_citation_id
from src.llm.cli_provider import invoke_local_cli
from src.llm.cloud_provider import invoke_cloud_llm
from src.models.state import AgentState

logger = logging.getLogger(__name__)

SYNTHESIS_SYSTEM_PROMPT = (
    "あなたは日本経済新聞社の金融アナリストAIです。与えられた「Live財務指標」のみを"
    "事実源として、日本語で簡潔な決算・株式分析レポートを作成してください。\n\n"
    "絶対厳守のルール:\n"
    "1. 数値・固有名詞・事実を含む一文には必ず文末に [mcp_id] 形式の引用タグを1つ付与すること。"
    "mcp_id は与えられたID一覧に実在するものだけを使い、絶対に新しいIDを作らないこと。\n"
    "2. 与えられた根拠に存在しない事実・数値を書かないこと（ハルシネーション厳禁）。\n"
    "3. 1文には根拠ID を1つだけ引用し、各文は句点「。」で終えること。\n"
    "4. 冒頭に Markdown 見出し「### 財務・業績分析レポート」を1つ置き、直後から本文のみを書くこと。"
    "前置き・謝辞・確認の質問は書かないこと。\n"
    "5. 与えられたID一覧に無い話題については書かないこと。\n"
    "6. 過去の新聞報道など古いスナップショットは一切参照・引用しないこと。レポートは常に最新の"
    "Live指標のみに基づいて書くこと。"
)


def _build_grounding_context(chunks: List[Dict[str, Any]], metrics: List[Dict[str, Any]]) -> str:
    """Renders Live financial metrics into an ID-labelled context block the
    model can cite from. Field names mirror what citation_verifier itself
    reconstructs for metrics (see src/citation/verifier.py), so a citation
    that quotes these numbers verbatim will pass the overlap/number checks.

    NOTE: retrieved news chunks (`doc_nikkei_*`, static historical snapshots)
    are intentionally NOT rendered here — the report must reflect only the
    latest Live data, not past news. The `chunks` parameter is kept for
    call-site compatibility but is no longer used as a grounding source.
    """
    lines: List[str] = []

    for m in metrics:
        ticker = m.get("ticker", "")
        if "per" in m and "pbr" in m:
            cid = f"mcp_val_{ticker}"
            lines.append(
                f"- ID: {cid} | {m.get('company_name', '')} 財務指標・バリュエーション\n"
                f"  内容: 予想PER {m.get('per')}倍、PBR {m.get('pbr')}倍、ROE（自己資本利益率）{m.get('roe_percent')}%、"
                f"TSR（株主総利回り）{m.get('tsr_percent')}%、評価ステータス『{m.get('valuation_status')}』"
            )
        elif "revenue_billion_jpy" in m:
            cid = f"mcp_disc_{ticker}"
            lines.append(
                f"- ID: {cid} | {m.get('company_name', '')} 決算開示情報\n"
                f"  内容: 売上高 {m.get('revenue_billion_jpy')}億円、営業利益 {m.get('operating_income_billion_jpy')}億円、"
                f"純利益 {m.get('net_income_billion_jpy')}億円、開示修正『{m.get('guidance_revision')}』"
            )
        elif "indicator" in m:
            mid = macro_citation_id(m.get("indicator", ""))
            lines.append(
                f"- ID: {mid} | マクロ環境指標（Live）\n"
                f"  内容: {m.get('indicator')} は現在 {m.get('value')}、トレンドは『{m.get('trend')}』"
            )

    if not lines:
        return ""
    return "## Live財務指標（引用可能な ID 一覧はこの中の ID のみ。過去の新聞報道は含まれない）\n" + "\n".join(lines)


def _build_synthesis_prompt(
    query: str,
    chunks: List[Dict[str, Any]],
    metrics: List[Dict[str, Any]],
    target_tickers: Optional[List[str]] = None,
    feedback_notes: str = "",
) -> Optional[str]:
    """Renders the grounded prompt shared by every LLM backend (local CLI and
    cloud). Returns None if there is no grounding context available at all
    (caller should skip the LLM call entirely in that case)."""
    context = _build_grounding_context(chunks, metrics)
    if not context:
        return None

    prompt_parts = [f"## ユーザーの質問\n{query}"]
    if target_tickers:
        prompt_parts.append(f"## 対象銘柄コード\n{', '.join(target_tickers)}")
    if feedback_notes:
        prompt_parts.append(f"## 監査フィードバック（前回の生成に対する指摘）\n{feedback_notes}")
    prompt_parts.append(context)
    prompt_parts.append("上記ルールに厳密に従い、レポート本文のみを日本語で出力してください。")
    return "\n\n".join(prompt_parts)


def synthesize_via_local_llm(
    query: str,
    chunks: List[Dict[str, Any]],
    metrics: List[Dict[str, Any]],
    target_tickers: Optional[List[str]] = None,
    feedback_notes: str = "",
) -> Optional[Tuple[str, str]]:
    """Builds a grounded prompt and asks a local AI CLI to write the report.

    Returns (draft_text, provider_name) on success, None if there is no
    context to ground on or every configured CLI provider failed.
    """
    prompt = _build_synthesis_prompt(query, chunks, metrics, target_tickers, feedback_notes)
    if prompt is None:
        return None

    completion = invoke_local_cli(prompt=prompt, system_prompt=SYNTHESIS_SYSTEM_PROMPT)
    if completion is None:
        return None
    logger.info(
        "synthesizer: local CLI provider=%s duration_ms=%.0f", completion.provider, completion.duration_ms
    )
    return completion.text, completion.provider


def synthesize_via_cloud_llm(
    query: str,
    chunks: List[Dict[str, Any]],
    metrics: List[Dict[str, Any]],
    target_tickers: Optional[List[str]] = None,
    feedback_notes: str = "",
) -> Optional[Tuple[str, str]]:
    """Cloud fallback (Azure OpenAI / Vertex AI) — only reached after local
    CLI has already failed/been skipped; see module docstring for priority.

    Returns (draft_text, provider_name) on success, None if there is no
    grounding context, no cloud provider is configured, or every configured
    provider failed.
    """
    if not settings.llm_cloud_fallback_order:
        return None

    prompt = _build_synthesis_prompt(query, chunks, metrics, target_tickers, feedback_notes)
    if prompt is None:
        return None

    completion = invoke_cloud_llm(prompt=prompt, system_prompt=SYNTHESIS_SYSTEM_PROMPT)
    if completion is None:
        return None
    logger.info(
        "synthesizer: cloud provider=%s duration_ms=%.0f", completion.provider, completion.duration_ms
    )
    return completion.text, completion.provider


def synthesize_grounded_response(
    query: str,
    chunks: List[Dict[str, Any]],
    metrics: List[Dict[str, Any]],
    target_tickers: List[str] = None,
    feedback_notes: str = "",
) -> str:
    """
    Deterministic fallback: generates a structured financial synthesis with
    explicit sentence-level chunk citations [chunk_id] via template
    assembly (no LLM call). Used when llm_backend == "template", or when
    every local CLI provider is unavailable/fails.

    NOTE: retrieved news chunks (`doc_nikkei_*`, static historical
    snapshots) are intentionally NOT cited here — only Live financial
    metrics are used, so the report never surfaces stale news data,
    matching the local-CLI grounding path in `synthesize_via_local_llm`.
    """
    if not metrics:
        return "ご指定の条件に合致する最新の財務データが見つかりませんでした。"

    response_lines = []
    response_lines.append("### 財務・業績分析レポート\n")

    # Add valuation & metric insights if available
    for m in metrics:
        if "per" in m and "pbr" in m:
            ticker = m.get("ticker", "")
            if target_tickers and ticker not in target_tickers:
                continue
            comp = m.get("company_name", "")
            per = m.get("per")
            pbr = m.get("pbr")
            roe = m.get("roe_percent")
            status = m.get("valuation_status", "FAIR")
            tsr = m.get("tsr_percent", 0.0)

            val_cid = f"mcp_val_{ticker}"
            response_lines.append(
                f"\n**{comp}（銘柄コード: {ticker}）の資本効率とバリュエーション指標**："
            )
            response_lines.append(
                f"現在の予想PERは{per}倍、PBRは{pbr}倍、ROE（自己資本利益率）は{roe}%となっています [{val_cid}]。"
            )
            response_lines.append(
                f"株主総利回り（TSR）は{tsr}%を記録しており、現在の市場評価ステータスは『{status}』と判定されます [{val_cid}]。"
            )
        elif "revenue_billion_jpy" in m:
            ticker = m.get("ticker", "")
            if target_tickers and ticker not in target_tickers:
                continue
            comp = m.get("company_name", "")
            disc_cid = f"mcp_disc_{ticker}"
            response_lines.append(
                f"\n**{comp}（銘柄コード: {ticker}）の最新決算開示**："
            )
            response_lines.append(
                f"{m.get('fiscal_year', '')}の売上高は{m.get('revenue_billion_jpy')}億円、"
                f"営業利益は{m.get('operating_income_billion_jpy')}億円、純利益は{m.get('net_income_billion_jpy')}億円です [{disc_cid}]。"
            )
        elif "indicator" in m:
            ind = m.get("indicator")
            val = m.get("value")
            trend = m.get("trend")
            mid = macro_citation_id(ind)
            response_lines.append(
                f"\n**マクロ環境動向**：{ind}は現在{val}となっており、トレンドは『{trend}』です [{mid}]。"
            )

    response_lines.append("\n---\n*本レポートはLive財務指標DB（yfinance等）に基づき自動生成・根拠検証されています。過去の新聞報道は使用していません。*")
    return "\n".join(response_lines)


def synthesizer_node(state: AgentState) -> Dict[str, Any]:
    """Generates draft response with sentence-level citations."""
    start_time = time.time()
    query = state.get("query", "")
    chunks = state.get("retrieved_chunks", [])
    metrics = state.get("financial_metrics", [])
    target_tickers = state.get("target_tickers", [])
    retry_count = state.get("retry_count", 0)

    feedback = ""
    if retry_count > 0:
        feedback = (
            "前回の監査で未検証引用またはハルシネーションが検出されたため、"
            "厳密に根拠が確認できる chunk_id のみを引用して再生成してください。"
        )

    provider_used = "template"
    draft: Optional[str] = None

    if settings.llm_backend == "local_cli":
        try:
            result = synthesize_via_local_llm(query, chunks, metrics, target_tickers, feedback)
        except Exception as exc:  # never let a CLI/prompt bug break the graph
            logger.warning("synthesizer: local LLM synthesis raised, falling back to template: %s", exc)
            result = None
        if result:
            draft, provider_used = result

    # Cloud fallback: only consulted if local CLI didn't produce a draft, and
    # only does anything if the operator opted in via llm_cloud_fallback_order.
    if not draft:
        try:
            cloud_result = synthesize_via_cloud_llm(query, chunks, metrics, target_tickers, feedback)
        except Exception as exc:  # never let an SDK/prompt bug break the graph
            logger.warning("synthesizer: cloud LLM synthesis raised, falling back to template: %s", exc)
            cloud_result = None
        if cloud_result:
            draft, provider_used = cloud_result

    if not draft:
        draft = synthesize_grounded_response(
            query=query,
            chunks=chunks,
            metrics=metrics,
            target_tickers=target_tickers,
            feedback_notes=feedback,
        )
        provider_used = "template"

    trace = state.get("execution_trace", [])
    trace.append({
        "node": "synthesizer",
        "duration_ms": round((time.time() - start_time) * 1000, 2),
        "retry_iteration": retry_count,
        "draft_length": len(draft),
        "llm_provider": provider_used,
    })

    return {
        "draft_response": draft,
        "final_response": draft,
        "execution_trace": trace,
    }
